In [2]:
import numpy as np

In [2]:
v = np.array([5,-2,4])

In [3]:
v

array([ 5, -2,  4])

matrices



In [4]:
m = np.array([[5,12,6],[-3,0,14]])

In [5]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

tensors

In [6]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [7]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [8]:
t = np.array([m1,m2])

In [9]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [10]:
t.shape

(2, 2, 3)

In [3]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [4]:
m3 = np.array([[5,3],[-2,4]])
m3

array([[ 5,  3],
       [-2,  4]])

In [5]:
m1.shape

(2, 3)

In [6]:
m3

array([[ 5,  3],
       [-2,  4]])

In [7]:
m3.shape

(2, 2)

In [8]:
m1+m3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [9]:
m1.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [11]:
np.dot(m3,m1)

array([[ 16,  60,  72],
       [-22, -24,  44]])